Multiple fixes: labeled data processing, dict data, fixes examples/02-basic_training.ipynb (#138)
* CorpusProcessor.process_corpus(): fix type hint for return value

Anyway, the return value could be wrong in case when both
document_splitter_fn and preprocessing_fn are None.

* test_e2e_indexing_searching: make test more robust

This test seems to succeed in CI but constantly fails on my machine
due to identical score for 2 passages. "Specific works"... would be
in the 4th retrieved passage:

  {'content': 'She met with Suzuki ... May 2006.', 'score': 24.421875, 'rank': 3, 'document_id': '82f22269-1fb8-479d-8...9f415dfdf9', 'passage_id': 45}
  {'content': 'Specific works that ... children.', 'score': 24.421875, 'rank': 4, 'document_id': '82f22269-1fb8-479d-8...9f415dfdf9', 'passage_id': 70}

* refactor: add RAGPretrainedModel._process_corpus() to reduce duplicate code

Avoid a few duplicate lines by adding a new method to make future changes easier.
With even more work it could be perhaps possible to make .index()
call .add_to_index() directly or other way round.

Note: it feels like 'split_documents' argument should be removed.
It would be easier to just check if 'document_splitter_fn' is None.
This is the way how 'preprocessing_fn' argument is already used.
'split_documents' is now left only on the public methods.

* Add unit test for prepare_training_data()

Add test main formats.
The test will currently fail. Fixes in later commits.

* RAGTrainer: fix parsing labeled pairs

_process_raw_labeled_pairs() expects items
in the format (query, passage, label).

Thus we can not differentiate triplets and labeled pairs
by using only length.

* training_data_processor: prevent out of bounds access with labeled pairs

Queries with no positives or no negatives would results in access
out of bounds.

* RAGTrainer: fix prepare_training_data() with dict content

Fix prepare_training_data() when the raw_data contains dicts.

This is the case e.g. when using similar pattern to
examples/02-basic_training.ipynb
where the data is first processed with CorpusProcessor.

* RAGTrainer: don't use class variables to allow multiple trainer objects

Use instance variables so that one can use multiple trainer objects
in same python process.

This also needed to fix test_prepare_training_data() test.
Otherwise only the first parametrized test will succeed.
Intance variables feels more natural here than e.g. some pytest
fixture change.

* training_data_processor: fix _process_raw_pairs() with dict items

Also here the item can contain dicts if use similar pattern to
examples/02-basic_training.ipynb
where the data is first processed with CorpusProcessor.

* Add tests/test_training.py

Test training using the examples/02-basic_training.ipynb
as an example. Alternative could be to test the actual notebook
but it would probably bring some additional dependencies.

* test_training: skip training test if CUDA is not available

Skip the test when CUDA is not available. This is the case in CI.
I'm not quite sure what would be needed to make it work without CUDA.

Currently, without CUDA the test fails with something like:

    Process Process-1:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/colbert/infra/launcher.py", line 134, in setup_new_process
        return_val = callee(config, *args)
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/colbert/training/training.py", line 55, in train
        colbert = torch.nn.parallel.DistributedDataParallel(colbert, device_ids=[config.rank],
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 712, in __init__
        self._log_and_throw(
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1037, in _log_and_throw
        raise err_type(err_msg)
    ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cpu')}.
    =========================== short test summary info ============================
    FAILED tests/test_training.py::test_training - AssertionError: Timout in training
    ============= 1 failed, 67 passed, 4 skipped in 269.14s (0:04:29) ==============

    Error: Process completed with exit code 1.

---------

Co-authored-by: Johannes Aalto <aalto.johannes@gmail.com>