test_training: skip training test if CUDA is not available
Skip the test when CUDA is not available. This is the case in CI.
I'm not quite sure what would be needed to make it work without CUDA.

Currently, without CUDA the test fails with something like:

    Process Process-1:
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
        self.run()
      File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
        self._target(*self._args, **self._kwargs)
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/colbert/infra/launcher.py", line 134, in setup_new_process
        return_val = callee(config, *args)
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/colbert/training/training.py", line 55, in train
        colbert = torch.nn.parallel.DistributedDataParallel(colbert, device_ids=[config.rank],
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 712, in __init__
        self._log_and_throw(
      File "/home/runner/.cache/pypoetry/virtualenvs/ragatouille-EqBdPU0M-py3.9/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1037, in _log_and_throw
        raise err_type(err_msg)
    ValueError: DistributedDataParallel device_ids and output_device arguments only work with single-device/multiple-device GPU modules or CPU modules, but got device_ids [0], output_device 0, and module parameters {device(type='cpu')}.
    =========================== short test summary info ============================
    FAILED tests/test_training.py::test_training - AssertionError: Timout in training
    ============= 1 failed, 67 passed, 4 skipped in 269.14s (0:04:29) ==============

    Error: Process completed with exit code 1.